name: Deploy Infrastructure Monitoring

on:
  push:
    branches: [main]
    paths:
      - 'cloudformation/**'
      - 'lambda-functions/**'
      - 'scripts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CloudFormation templates
        run: |
          pip install cfn-lint
          cfn-lint cloudformation/*.yaml

      - name: Deploy Main Stack
        run: |
          bash scripts/deploy.sh --environment prod --skip-tests

      - name: Create Dashboards
        run: python scripts/create-dashboards.py --environment prod
