name: Deploy Infrastructure Monitoring

on:
  push:
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CloudFormation templates
        run: |
          pip install cfn-lint
          cfn-lint cloudformation/*.yaml --ignore-checks W2501 W1011 || exit_code=$?
          # ignore warning-only exit code (4): treat only non-0/4 as error
          if [ "$exit_code" -ne 0 ] && [ "$exit_code" -ne 4 ]; then
          exit $exit_code
          fi

      - name: Deploy Main Stack
        run: |
          bash scripts/deploy.sh --environment prod --skip-tests

      - name: Create Dashboards
        run: echo "Dashboard creation skipped - will be added manually"
        # run: python scripts/create-dashboards.py --environment prod
