name: Validate Templates

on:
  push:
    paths:
      - 'cloudformation/**.yaml'
      - '.github/workflows/validate.yml'
      - 'lambda-functions/**.py'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint templates
        run: cfn-lint cloudformation/*.yaml